# Add MABL_CI_KEY and MABL_REST_API_KEY to CircleCI Environment Variables before executing
# MABL_CI_KEY==mabl CI/CD Integration Key
# MABL_REST_API_KEY==mabl CLI API Key

version: 2.1

orbs:
  # Run tests on mabl cloud
  mabl-trigger-tests: mabl/trigger-tests@1.0.8

workflows:
  version: 2
  tests_tests_tests:
    jobs:
      - unit-tests
      - mabl-local
      - deploy-to-qa:
          requires:
              - unit-tests
              - mabl-local
      - mabl-cloud:
          requires:
              - deploy-to-qa 
      - deploy-to-prod:
          type: approval
          requires:
              - mabl-cloud

jobs:
  mabl-local:
    machine: true
    steps:
      - run: docker run -e MABL_REST_API_KEY=$MABL_CLI_KEY --rm mablhq/mabl-cli-chromium \
                tests run --id b4eEntmxZ1x0mB4ML2Cr9g-j --workspace-id kJMlpeP11w5Hz8oDkVAm2g-w --headless
    
    ### Modified snippet to run local tests within Docker executor
    # working_directory: /home/mabl
    # docker:
    #   - image: mablhq/mabl-cli-chromium:1.29.19
    #     environment:
    #       # Optional
    #         # MABL_HTTP_PROXY: IP Address:port
    #         # MABL_HTTP_PROXY_MODE: false
    #         # MABL_SSL_VERIFY: true
    #     entrypoint: bash
    # steps: 
    #   - run: bash run_command_with_auth.sh tests run \
    #            --workspace-id kJMlpeP11w5Hz8oDkVAm2g-w \
    #            --environment-id nwwfqkMqWbqq3jPFMfI6sw-e \
    #            --id b4eEntmxZ1x0mB4ML2Cr9g-j \
    #            --headless

  mabl-cloud:
    # mabl documentation lists machine executor, however using Docker executor will save on build credits and speed up builds.
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_CI_KEY
          application-id: MjGqZ5E2OCsgxIeS66cF9w-a
          environment-id: nwwfqkMqWbqq3jPFMfI6sw-e
          # browsers: chrome
          # labels: myPlanLabel
          # mabl-branch: developmentBranch

  unit-tests: 
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - run: "sleep 5"

  deploy-to-qa: 
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - run: "sleep 5" 
  
  deploy-to-prod: 
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - run: "sleep 10"
    