version: 2.1

orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.8

workflows:
  version: 2
  tests_tests_tests:
    jobs:
      - mabl-local
      # - mabl-cloud

jobs:
  mabl-cloud:
    docker:
      - image: cimg/base:2021.04
      - resource_class: small
    # machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_CI_KEY
          application-id: MjGqZ5E2OCsgxIeS66cF9w-a
          environment-id: nwwfqkMqWbqq3jPFMfI6sw-e
  
  mabl-local:
    docker:
      - image: mablhq/mabl-cli-chromium
        environment:
          MABL_REST_API_KEY: $MABL_CLI_KEY
          # MABL_CLI_NAME: mabl
          # Optional
            # MABL_HTTP_PROXY: IP Address:port
            # MABL_HTTP_PROXY_MODE: false
            # MABL_SSL_VERIFY: true
        entrypoint: bash
        user: mabl
    steps:

      - run: env
      - run: ls
      - run: pwd
      - run: bash run_command_with_auth.sh tests run --id b4eEntmxZ1x0mB4ML2Cr9g-j --workspace-id kJMlpeP11w5Hz8oDkVAm2g-w --headless
    

    # machine: true
    # steps:
    #   - run: docker run -e MABL_REST_API_KEY=$MABL_CLI_KEY --rm mablhq/mabl-cli-chromium \
    #             tests run --id b4eEntmxZ1x0mB4ML2Cr9g-j --workspace-id kJMlpeP11w5Hz8oDkVAm2g-w --headless